[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "subtitleflow"
version = "0.1.1"
description = "璺ㄥ钩鍙板瓧骞曞悎骞朵笌缈昏瘧宸ュ叿"
requires-python = ">=3.12"
dependencies = ["PySide6-Essentials==6.11.2", "keyring==25.6.0"]

[project.scripts]
subtitleflow = "subtitleflow.gui:main"

[tool.setuptools.packages.find]
include = ["subtitleflow*"]
