"""Compact single-window layout. API configuration stays in one saved dialog."""
from PySide6.QtCore import Qt, QTimer
from PySide6.QtGui import QIcon
from PySide6.QtWidgets import (
    QWidget, QFrame, QVBoxLayout, QHBoxLayout, QFormLayout, QLabel, QPushButton,
    QLineEdit, QComboBox, QDoubleSpinBox, QSpinBox, QCheckBox, QDialog, QMenu, QProgressBar,
)
from .design import apply, logo


def row(*widgets):
    layout = QHBoxLayout()
    layout.setSpacing(10)
    for widget in widgets:
        layout.addWidget(widget)
    return layout


def label(text, kind="muted"):
    widget = QLabel(text)
    widget.setObjectName(kind)
    return widget


def button(text, action, kind=""):
    widget = QPushButton(text)
    if kind:
        widget.setObjectName(kind)
    widget.clicked.connect(action)
    return widget


def numeric(value, low, high, suffix):
    widget = QDoubleSpinBox()
    widget.setRange(low, high)
    widget.setDecimals(1)
    widget.setValue(value)
    widget.setSuffix(suffix)
    widget.setFixedWidth(115)
    return widget


def build(window, table_type):
    w = window
    apply()
    w.setWindowIcon(QIcon(logo()))
    w.resize(960, 760)
    w.setMinimumSize(820, 670)
    root = QWidget()
    w.setCentralWidget(root)
    outer = QVBoxLayout(root)
    outer.setContentsMargins(28, 22, 28, 20)
    outer.setSpacing(17)
    header = QHBoxLayout()
    mark = QLabel()
    mark.setPixmap(logo(44))
    header.addWidget(mark)
    brand = QVBoxLayout()
    brand.setSpacing(2)
    brand.addWidget(label("SubtitleFlow", "brand"))
    brand.addWidget(label("让字幕处理，简单一点。", "subtitle"))
    header.addLayout(brand)
    header.addStretch()
    w.translation_button = button("翻译设置", w.show_translation)
    header.addWidget(w.translation_button)
    more = QPushButton("更多")
    more.setObjectName("quiet")
    menu = QMenu(more)
    w.restore_button = menu.addAction("恢复未完成任务", w.restore)
    menu.addAction("软件更新", w.show_update)
    menu.addSeparator()
    menu.addAction("关于与版权", w.about)
    more.setMenu(menu)
    header.addWidget(more)
    outer.addLayout(header)

    files = QFrame()
    files.setObjectName("card")
    file_layout = QVBoxLayout(files)
    file_layout.setContentsMargins(18, 15, 18, 8)
    file_layout.setSpacing(10)
    bar = QHBoxLayout()
    bar.addWidget(label("字幕文件", "section"))
    w.file_count = label("0 个文件")
    bar.addWidget(w.file_count)
    bar.addStretch()
    w.clear_button = button("清空", w.clear_files, "quiet")
    w.add_button = button("＋ 添加字幕", w.choose_files)
    bar.addWidget(w.clear_button)
    bar.addWidget(w.add_button)
    file_layout.addLayout(bar)
    w.table = table_type()
    w.table.files_dropped.connect(w.add_files)
    w.table.verticalHeader().hide()
    w.table.verticalHeader().setDefaultSectionSize(46)
    w.table.setShowGrid(False)
    w.table.setAlternatingRowColors(True)
    w.table.setMinimumHeight(170)
    file_layout.addWidget(w.table, 1)
    outer.addWidget(files, 1)

    w.settings_group = QFrame()
    w.settings_group.setObjectName("card")
    settings = QVBoxLayout(w.settings_group)
    settings.setContentsMargins(20, 17, 20, 16)
    settings.setSpacing(14)
    w.mode = QComboBox()
    for text, mode in (("合并后翻译", "both"), ("仅合并字幕", "merge"), ("仅翻译字幕", "translate"), ("SRT → FCPXML", "fcpxml")):
        w.mode.addItem(text, mode)
    w.mode.setMinimumWidth(185)
    mainrow = row(label("处理方式", "section"), w.mode)
    mainrow.addStretch()
    w.advanced_button = button("高级选项", lambda: w.advanced.setVisible(not w.advanced.isVisible()), "quiet")
    mainrow.addWidget(w.advanced_button)
    settings.addLayout(mainrow)
    w.target = numeric(10, .1, 3600, " 秒")
    w.silence = numeric(3, .1, 120, " 秒")
    w.tolerance = numeric(25, 0, 200, " %")
    w.merge_row = QWidget()
    merge = row(label("目标时长"), w.target, label("静音断句"), w.silence)
    merge.setContentsMargins(0, 0, 0, 0)
    merge.addStretch()
    w.merge_row.setLayout(merge)
    settings.addWidget(w.merge_row)
    w.mode_note = label("")
    w.mode_note.setWordWrap(True)
    settings.addWidget(w.mode_note)
    w.export_xml = QCheckBox("同时导出 FCPXML")
    w.fps = QComboBox()
    w.fps.addItems(["23.976", "24", "25", "29.97", "30", "50", "59.94", "60"])
    w.fps.setCurrentText("25")
    w.fps_label = label("项目帧率")
    exportrow = row(w.export_xml)
    exportrow.addStretch()
    exportrow.addWidget(w.fps_label)
    exportrow.addWidget(w.fps)
    settings.addLayout(exportrow)
    w.advanced = QWidget()
    advanced = QVBoxLayout(w.advanced)
    advanced.setContentsMargins(0, 0, 0, 0)
    w.ai = QCheckBox("AI 辅助断句")
    advrow = row(label("合并软容差"), w.tolerance, w.ai)
    advrow.addStretch()
    advanced.addLayout(advrow)
    w.advanced.hide()
    settings.addWidget(w.advanced)
    w.output = QLineEdit()
    from pathlib import Path
    w.output.setText(str(Path.home() / "SubtitleFlow输出"))
    w.output.setPlaceholderText("选择结果保存位置")
    settings.addLayout(row(label("保存到"), w.output, button("选择", w.choose_output)))
    outer.addWidget(w.settings_group)
    w.progress = QProgressBar()
    w.progress.setTextVisible(False)
    w.progress.setValue(0)
    outer.addWidget(w.progress)
    footer = QHBoxLayout()
    w.status = label("拖入字幕，即可开始")
    w.status.setWordWrap(True)
    footer.addWidget(w.status, 1)
    w.open_button = button("查看结果", w.open_output, "quiet")
    w.open_button.hide()
    w.retry_button = button("重试", lambda: w.start(w.last_root), "quiet")
    w.retry_button.setEnabled(False)
    w.retry_button.hide()
    w.cancel_button = button("取消", w.cancel_job)
    w.cancel_button.setEnabled(False)
    w.cancel_button.hide()
    w.start_button = button("开始处理", lambda: w.start(), "primary")
    for item in (w.open_button, w.retry_button, w.cancel_button, w.start_button):
        footer.addWidget(item)
    outer.addLayout(footer)

    w.api_dialog = QDialog(w)
    w.api_dialog.setWindowTitle("翻译设置")
    w.api_dialog.setMinimumWidth(600)
    api_layout = QVBoxLayout(w.api_dialog)
    api_layout.setContentsMargins(24, 24, 24, 24)
    api_layout.setSpacing(18)
    api_layout.addWidget(label("连接你的翻译服务", "section"))
    api_layout.addWidget(label("配置一次，下次直接使用。支持 OpenAI 兼容接口。"))
    form = QFormLayout()
    form.setSpacing(13)
    w.base = QLineEdit()
    w.base.setPlaceholderText("https://服务地址/v1")
    w.key = QLineEdit()
    w.key.setEchoMode(QLineEdit.Password)
    w.key.setPlaceholderText("API Key")
    w.model = QComboBox()
    w.model.setEditable(True)
    w.model.setInsertPolicy(QComboBox.NoInsert)
    w.model.lineEdit().setPlaceholderText("从列表选择，或手动输入模型")
    w.models_button = button("加载模型", w.load_models)
    form.addRow("服务地址", w.base)
    form.addRow("API Key", w.key)
    form.addRow("模型", row(w.model, w.models_button))
    w.remember = QCheckBox("安全记住密钥")
    w.remember.setToolTip("保存到 Windows 凭据管理器 / macOS 钥匙串")
    form.addRow("", w.remember)
    w.local_cert = QCheckBox("允许本机自签名证书")
    w.local_cert.setToolTip("仅适用于 localhost 或回环 IP，默认关闭")
    form.addRow("", w.local_cert)
    w.batch = QSpinBox()
    w.batch.setRange(1, 200)
    w.batch.setValue(20)
    form.addRow("每批字幕数", w.batch)
    api_layout.addLayout(form)
    w.api_status = label("填写地址和密钥后，点击加载模型。")
    w.api_status.setWordWrap(True)
    api_layout.addWidget(w.api_status)
    w.test_button = button("测试连接", w.test_api)
    bottom = row(w.test_button)
    bottom.addStretch()
    bottom.addWidget(button("保存", w.save_translation, "primary"))
    api_layout.addLayout(bottom)
    w.models_timer = QTimer(w)
    w.models_timer.setSingleShot(True)
    w.models_timer.setInterval(400)
    w.models_timer.timeout.connect(lambda: w.load_models(automatic=True))
    w.last_models_identity = None
    w.models_loading = False
    w.base.editingFinished.connect(w.schedule_models)
    w.key.editingFinished.connect(w.schedule_models)
    w.local_cert.toggled.connect(w.schedule_models)

    w.update_dialog = QDialog(w)
    w.update_dialog.setWindowTitle("软件更新")
    update_layout = QVBoxLayout(w.update_dialog)
    update_layout.setContentsMargins(24, 24, 24, 24)
    update_layout.setSpacing(14)
    from . import __version__
    update_layout.addWidget(label("SubtitleFlow " + __version__, "section"))
    update_layout.addWidget(label("启动时自动检查新版本，确认后下载并安装。"))
    from .updates import DEFAULT_REPO
    w.repo = QLineEdit(DEFAULT_REPO)
    w.repo.setPlaceholderText("owner/repository")
    update_layout.addWidget(w.repo)
    w.update_button = button("检查更新", lambda: w.check_update(False))
    update_layout.addWidget(w.update_button)
    w.update_status = label("更新会在字幕任务完成后安装。")
    update_layout.addWidget(w.update_status)
    w.mode.currentIndexChanged.connect(w.refresh_mode)
    w.export_xml.toggled.connect(w.refresh_mode)
    w.refresh_mode()
